"""initial_schema

Revision ID: 945698d91dbc
Revises:
Create Date: 2026-04-28 22:14:04.951664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "945698d91dbc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=True),
        sa.Column("iso2", sa.String(length=2), nullable=True),
        sa.Column("iso3", sa.String(length=3), nullable=True),
        sa.Column("m49", sa.String(length=5), nullable=True),
        sa.Column("un_member_since", sa.Date(), nullable=True),
        sa.Column("un_member_end", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iso2"),
        sa.UniqueConstraint("iso3"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("body", sa.String(length=2), nullable=False),
        sa.Column("meeting_number", sa.Integer(), nullable=False),
        sa.Column("session", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=50), nullable=True),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("ocr_quality_score", sa.Float(), nullable=True),
        sa.Column("ocr_quality_label", sa.String(length=10), nullable=True),
        sa.Column("ods_used", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_table(
        "resolutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("draft_symbol", sa.Text(), nullable=False),
        sa.Column("adopted_symbol", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.String(length=2), nullable=False),
        sa.Column("session", sa.Integer(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("agenda_title", sa.Text(), nullable=True),
        sa.Column("committee_report", sa.Text(), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("crunsc_id", sa.String(length=30), nullable=True),
        sa.Column("undl_id", sa.String(length=30), nullable=True),
        sa.Column("undl_link", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crunsc_id"),
    )
    op.create_table(
        "amendments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resolution_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("proposed_by_country_id", sa.Integer(), nullable=True),
        sa.Column("oral_correction", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposed_by_country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolution_id"],
            ["resolutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum("agenda_item", "other_item", name="item_type_enum"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("agenda_number", sa.Integer(), nullable=True),
        sa.Column("sub_item", sa.String(length=10), nullable=True),
        sa.Column("continued", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "position", name="uq_item_position"),
    )
    op.create_table(
        "resolution_citations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("citing_id", sa.Integer(), nullable=False),
        sa.Column("cited_symbol", sa.Text(), nullable=False),
        sa.Column("cited_id", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["cited_id"], ["resolutions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["citing_id"], ["resolutions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("citing_id", "cited_symbol", name="uq_citation"),
    )
    op.create_table(
        "speakers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("organization", sa.String(length=400), nullable=True),
        sa.Column("role", sa.String(length=500), nullable=True),
        sa.Column("title", sa.String(length=20), nullable=True),
        sa.Column("first_seen_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "country_id", "organization", name="uq_speaker"),
    )
    op.create_table(
        "permanent_representatives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("speaker_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("salutation", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("undl_id", sa.String(length=30), nullable=True),
        sa.Column("undl_link", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["country_id"], ["countries.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["speaker_id"], ["speakers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("undl_id"),
    )
    op.create_table(
        "sc_representatives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("speaker_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("salutation", sa.String(length=20), nullable=True),
        sa.Column("sc_president", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("undl_id", sa.String(length=30), nullable=True),
        sa.Column("undl_link", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["country_id"], ["countries.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["speaker_id"], ["speakers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("undl_id"),
    )
    op.create_table(
        "speeches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("speaker_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("on_behalf_of", sa.String(length=300), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("position_in_document", sa.Integer(), nullable=False),
        sa.Column("position_in_item", sa.Integer(), nullable=False),
        sa.Column("speech_type", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["document_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stage_directions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "direction_type",
            sa.Enum(
                "adoption",
                "decision",
                "suspension",
                "resumption",
                "adjournment",
                "silence",
                "language_note",
                "other",
                name="direction_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("position_in_document", sa.Integer(), nullable=False),
        sa.Column("position_in_item", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["document_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("resolution_id", sa.Integer(), nullable=False),
        sa.Column(
            "vote_type",
            sa.Enum("consensus", "recorded", name="vote_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "vote_scope",
            sa.Enum(
                "whole_resolution", "paragraph", "amendment", name="vote_scope_enum"
            ),
            nullable=False,
        ),
        sa.Column("paragraph_number", sa.Integer(), nullable=True),
        sa.Column("yes_count", sa.Integer(), nullable=True),
        sa.Column("no_count", sa.Integer(), nullable=True),
        sa.Column("abstain_count", sa.Integer(), nullable=True),
        sa.Column("total_non_voting", sa.Integer(), nullable=True),
        sa.Column("total_ms", sa.Integer(), nullable=True),
        sa.Column("vote_note", sa.Text(), nullable=True),
        sa.Column("undl_id", sa.String(length=20), nullable=True),
        sa.Column("undl_link", sa.String(length=500), nullable=True),
        sa.Column("position_in_item", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["document_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolution_id"],
            ["resolutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "country_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vote_id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column(
            "vote_position",
            sa.Enum(
                "yes",
                "no",
                "abstain",
                "absent",
                "non_voting",
                name="vote_position_enum",
            ),
            nullable=False,
        ),
        sa.Column("permanent_member", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vote_id"],
            ["votes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vote_id", "country_id", name="uq_country_vote"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("country_votes")
    op.drop_table("votes")
    op.drop_table("stage_directions")
    op.drop_table("speeches")
    op.drop_table("sc_representatives")
    op.drop_table("permanent_representatives")
    op.drop_table("speakers")
    op.drop_table("resolution_citations")
    op.drop_table("document_items")
    op.drop_table("amendments")
    op.drop_table("resolutions")
    op.drop_table("documents")
    op.drop_table("countries")
    # ### end Alembic commands ###
